export interface Sense {
    creator : string,
    lastUpdate : string,
    creationDate : string,
    confidence : number,
    sense : string,
    senseInstanceName : string,
    lexicalEntry : string,
    lexicalEntryInstanceName : string,
    pos : string,
    lemma : string,
    hasChildren : boolean,
    label : string,
    definition : string,
    note : string,
    usage : string,
    concept : string,
    conceptInstanceName : string,
    description : string,
    gloss : string,
    senseExample : string, 
    senseTranslation : string
}